name: Push code to AWS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: github-action
          aws-region: ${{ env.AWS_REGION }}
  
      - name: Sync specific files to S3 bucket
        run: |
          aws s3 cp index.html s3://${{ env.S3_BUCKET_NAME }}/
      - name: Create Invalidation
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.CF_DIST_ID }} --paths "/*"
